services:
  bun:
    image: oven/bun:latest
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
      - 4321:4321
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/NoWaste
    working_dir: /usr/src/app
    command: bun docker:dev
    
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: NoWaste
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - postgres